config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :rooms, only: [:new, :create, :show, :destroy] do
    resources :posts, only: [:create, :destroy]
  end
  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
      {id: 1, name: '---'},
      {id: 2, name: '男性'},
      {id: 3, name: '女性'},
      {id: 4, name: 'どちらでもない'},
  ]

  include ActiveHash::Associations
  has_many :user
end

app/models/job.rb
class Job < ActiveHash::Base
  self.data = [
      {id: 1, name: '---'},
      {id: 2, name: '公務員'},
      {id: 3, name: '経営者・役員'},
      {id: 4, name: '会社員'},
      {id: 5, name: '自営業'},
      {id: 6, name: '自由業'},
      {id: 7, name: '専業主婦'},
      {id: 8, name: 'パート・アルバイト'},
      {id: 9, name: '学生'},
      {id: 10, name: 'その他'},
  ]

  include ActiveHash::Associations
  has_many :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :likes
  has_many :users, through: :likes
  belongs_to :room
  has_one_attached :image
  
  with_options length: { maximum: 200 } do
    validates :post_a, presence: true, unless: :post_b?
    validates :post_b, presence: true, unless: :post_a?
  end

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '---'},
      {id: 2, name: '北海道'},
      {id: 3, name: '青森県'},
      {id: 4, name: '岩手県'},
      {id: 5, name: '宮城県'},
      {id: 6, name: '秋田県'},
      {id: 7, name: '山形県'},
      {id: 8, name: '福島県'},
      {id: 9, name: '茨城県'},
      {id: 10, name: '栃木県'},
      {id: 11, name: '群馬県'},
      {id: 12, name: '埼玉県'},
      {id: 13, name: '千葉県'},
      {id: 14, name: '東京都'},
      {id: 15, name: '神奈川県'},
      {id: 16, name: '新潟県'},
      {id: 17, name: '富山県'},
      {id: 18, name: '石川県'},
      {id: 19, name: '福井県'},
      {id: 20, name: '山梨県'},
      {id: 21, name: '長野県'},
      {id: 22, name: '岐阜県'},
      {id: 23, name: '静岡県'},
      {id: 24, name: '愛知県'},
      {id: 25, name: '三重県'},
      {id: 26, name: '滋賀県'},
      {id: 27, name: '京都府'},
      {id: 28, name: '大阪府'},
      {id: 29, name: '兵庫県'},
      {id: 30, name: '奈良県'},
      {id: 31, name: '和歌山県'},
      {id: 32, name: '鳥取県'},
      {id: 33, name: '島根県'},
      {id: 34, name: '岡山県'},
      {id: 35, name: '広島県'},
      {id: 36, name: '山口県'},
      {id: 37, name: '徳島県'},
      {id: 38, name: '香川県'},
      {id: 39, name: '愛媛県'},
      {id: 40, name: '高知県'},
      {id: 41, name: '福岡県'},
      {id: 42, name: '佐賀県'},
      {id: 43, name: '長崎県'},
      {id: 44, name: '熊本県'},
      {id: 45, name: '大分県'},
      {id: 46, name: '宮崎県'},
      {id: 47, name: '鹿児島県'},
      {id: 48, name: '沖縄県'}
  ]

  include ActiveHash::Associations
  has_many :user
end

app/models/room.rb
class Room < ApplicationRecord

  belongs_to :user
  has_many :posts, dependent: :destroy

  with_options presence: true do
    validates :agenda, length: { maximum: 50 }
    with_options length: { maximum: 20 } do
    validates :stanceA
    validates :stanceB
    end
    validates :user_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts
  has_many :likes
  has_many :favorites, through: :likes, source: :post
  has_many :rooms, through: :posts

  def like_this(clicked_post)
    self.likes.find_or_create_by(post: clicked_post)
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  belongs_to :gender
  belongs_to :job

    with_options presence: true do
    validates :name, length: { maximum: 10 }
    validates :birthday
  end
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze }

  with_options numericality: { other_than: 1 } do
  validates :prefecture_id
  validates :gender_id
  validates :job_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth if Rails.env.production?
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :birthday, :gender_id, :prefecture_id, :job_id])
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    if current_user.like_this(clicked_post)
      flash[:success] = '投稿に「いいね！」しました。'
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = 'すでに「いいね！」しています'
      redirect_back(fallback_location: root_path)
      # 「いいね！」削除ボタンを実装すると、↑上記の2行は不要になります
    end
  end

  def destroy
    current_user.likes.find_by(post_id: params[:post_id]).destroy
    flash[:danger] = '「いいね！」を解除しました。'
    redirect_back(fallback_location: root_path)
  end

  private

  def clicked_post
    Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.create(post_params)
    redirect_to "/rooms/#{@post.room.id}"
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to "/rooms/#{@post.room.id}"
  end

  private

  def post_params
    params.require(:post).permit(:post_a, :post_b, :image).merge(user_id: current_user.id, room_id: params[:room_id])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_room, only: [:show, :destroy]
  before_action :restriction_user, only: [:destroy]

  def index
    @room = Room.all.order("created_at DESC")
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_path(@room.id)
    else
      render :new
    end
  end

  def show
    @post = Post.new
    @posts = @room.posts.includes(:user)
  end

  def destroy
    @room.destroy
    redirect_to root_path
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:agenda, :stanceA, :stanceB).merge(user_id: current_user.id)
  end

  def restriction_user
    unless current_user.id == @room.user_id
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BreakpointApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= render "shared/header" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/index.html.erb
<div class="room-contents">

<%= link_to('rooms/new', url: new_room_path, class: "create-room-btn") do %>
<div class="create-room-contents">
  <%= image_tag '会議アイコン3.png', size: '60x60', class: "create-room-icon" %>
  <p class="create-room-text">チャットルームを作成する</p>
</div>
<% end %>

<div class="room_contents">
 <h1 class="title">チャットルーム一覧</h1>
 <ul class="room-lists">
  <% @room.each do |room| %>
    <li class="room-list">
    <div class="room-title">
      <%= image_tag'会話アイコン.png', size: '30x30', class: "room-icon" %>
      <%= room.agenda %>
    </div>
    <%= link_to room_path(room.id), class:"room-name" do %>
      <div class="enter-room-btn">入室する</div>
    <% end %>
    <li>
  <% end %>
 </ul>
 </div>
</div>

app/views/rooms/new.html.erb
<div class="new-create-contents">
<h1 class="create-room-title">チャットルームの作成</h1>
<%= form_with model: @room, url: rooms_path, local: true do |f| %>

<%= render 'shared/error_messages', model: f.object %>

<div class="create-contents-title">
  <div class="room-agenda">
    <label for = "room_agenda">ルームのアジェンダを設定</label>
  </div>
  <%= f.text_area :agenda, class:"room-agenda", placeholder:"例) あなたは犬派？それとも猫派？" %>

  <div class="create-contents-title">2つのスタンスを設定</div>
    <div class="stance-contents-title">
      <div class="stance-A-title">
      <label for = "room_stanceA">スタンスA</label>
      </div>
      <%= f.text_area :stanceA, class:"room-stanseA", placeholder:"例) 犬派" %>
    </div>

    <div class="stance-contents-title">
      <div class="stance-B-title">
      <label for = "room_stanceB">スタンスB</label>
      </div>
      <%= f.text_area :stanceB, class:"room-stanceB", placeholder:"例) 猫派" %>
    </div>

  <div class="room-create-btn-contents">
    <%= f.submit "ルーム作成" ,class:"room-create-btn" %>
    <%=link_to 'もどる', root_path, class:"back-btn" %>
  </div>

  </div>
  </div>
<% end %>
</div>

app/views/rooms/show.html.erb
<div class="chat-room-contents">

<div class="room-titles">
  <div class="agenda-content">
    <div class="contents-title">このルームのアジェンダ</div>
  <div class="agenda">
    <%= @room.agenda %>
  </div>
</div>

<div class="content">
  <div class="stance-contents">
    <div class="contents-title">このルームのスタンス</div>
    <div class="stance-content">
      <div class="stance-title">スタンスA</div>
      <div class="stance">
        <%= @room.stanceA %>
      </div>
    </div>
    
    <div class="stance-content">
      <div class="stance-title">スタンスB</div>
      <div class="stance">
        <%= @room.stanceB %>
      </div>
    </div>
  </div>

<% if user_signed_in? && current_user.id == @room.user.id %>
<ul class="owner-menu">
  <li class="owner-menu-list">
    <a href="#" class="init-bottom">
      メニュー<%= image_tag '矢印アイコン 下4.png', size: '12x12', class: "owner-menu-icon" %>
    </a>
  <ul class="second-menu">
    <li>
    <%= link_to room_path(@room.id), method: :delete, class: "room-destroy" do %>
      <%= image_tag '562_ex_f.png', size: '16x16' %>
      ルーム削除
    <% end %>
    </li>
  </ul>
  </li>
</ul>
<% end %>

</div>

</div>

<div class="chat-contents">

  <div class="chat-view">
  
  <div class="coments">
  <% @posts.each do |post| %>
  <div class="post-contents">
    <div class="side_a">
    <% if post.post_b == nil %>
      <div class="speach_bubble_left">
        <%= post.post_a %>
        <div  class="post-image">
          <%= image_tag post.image.variant(resize: '80x80') if post.image.attached? %>
        </div>
        <div class="user-states">
          <div class="user-name">
            name:<%= post.user.name %>
          </div>
          <%= post.user.gender.name %>
          <%= post.user.prefecture.name %>
          <%= post.user.job.name %>
        </div>

          <% if current_user.id != post.user.id %>
　　　　　　
          <% if current_user.favorites.include?(post) %>
          <div class="like_btn_cancel">
            <%= form_with(model: @like, url: like_path(id: post.id), local: true, method: :delete) do |f| %>
              <%= f.hidden_field :post_id, value: post.id %>
              <%= f.submit 'いいね解除' %>
            <% end %>
          </div>
          <% else %>
          <div class="like_btn">
            <%= form_with(model: @like, url: likes_path, local: true) do |f| %>
              <%= f.hidden_field :post_id, value: post.id %>
              <%= f.submit 'いいね' %>
            <% end %>
          </div>
          <% end %>

          <% end %>

        <% if current_user.id == post.user_id %>
          <%= link_to room_post_path(@room, post), method: :delete, class: "post-destroy" do %>
            <%= image_tag '562_ex_f.png', size: '13x13' %>
            削除
          <% end %>
        <% end %>

      </div>
    <% end %>
    </div>
    <div class="side_b">
    <% if post.post_a == nil %>
      <div class="speach_bubble_right">
        <%= post.post_b %>
        <div  class="post-image">
          <%= image_tag post.image.variant(resize: '80x80') if post.image.attached? %>
        </div>
        <div class="user-states">
          <div class="user-name">
            name:<%= post.user.name %>
          </div>
          <%= post.user.gender.name %>
          <%= post.user.prefecture.name %>
          <%= post.user.job.name %>
        </div>

        <% if current_user.id == post.user_id %>
          <%= link_to room_post_path(@room, post), method: :delete, class: "post-destroy" do %>
            <%= image_tag '562_ex_f.png', size: '13x13' %>
            削除
          <% end %>
        <% end %>

      </div>
    <% end %>
    </div>
  </div>
  <% end %>
  </div>

  </div>

  <div class="chat-form">
    <input type="radio" name="tab_name" id="tab_a">
    <label class="tab_content" for="tab_a">スタンスA</label>
    <div class="chat-content">
      
      <%= form_with(model: [@room, @post], local: true) do |f| %>
      <div class='preview', id="preview-list_1"></div>
      <div class="form-input">
        <%= f.text_area :post_a, class: 'form-comment', placeholder: 'スタンスAとしてコメント' %>
        <label class="form-image">
          <%= image_tag '写真アイコン4.png', size: '30x30' %>
          <span class="image-file">画像を選択</span>
          <%= f.file_field :image, class: 'hidden', id: 'post_image_1' %>
        </label>
      </div>
      <%= f.submit 'コメントを投稿する', class: 'form-submit' %>
      <% end %>

    </div>
    <input type="radio" name="tab_name" id="tab_b">
    <label class="tab_content" for="tab_b">スタンスB</label>
    <div class="chat-content">
      
      <%= form_with(model: [@room, @post], local: true) do |f| %>
      <div class='preview', id="preview-list_2"></div>
      <div class="form-input">
        <%= f.text_area :post_b, class: 'form-comment', placeholder: 'スタンスBとしてコメント' %>
        <label class="form-image">
          <%= image_tag '写真アイコン4.png', size: '30x30' %>
          <span class="image-file">画像を選択</span>
          <%= f.file_field :image, class: 'hidden', id: 'post_image_2' %>
        </label>
      </div>
      <%= f.submit 'コメントを投稿する', class: 'form-submit' %>
      <% end %>

    </div>
  </div>

</div>

</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
 <div>
  <%= link_to "/", class: "title-logo-content" do %>
  <%= image_tag '驚き閃きそんなアイコン.png', size: '40x40' %>
  <div class="title-logo">BreakPoint</div>
  <% end %>
 </div>
 <ul class="lists-user">
 <% if user_signed_in? %>
  <li class="user-content-lists"><%= link_to current_user.name, "#", class: "header-right" %></li>
  <li class="user-content-lists"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "header-right" %></li>
 <% else %>
  <li class="user-content-lists"><%= link_to 'ログイン',  new_user_session_path, class: "header-right" %></li>
  <li class="user-content-lists"><%= link_to '新規登録', new_user_registration_path, class: "header-right" %></li>
 <% end %>
 </ul>
</header>